name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Testing"
            echo "Over two lines"
      - name: Print exit
        run: echo "Now finished"
